[package]
name = "veriwasi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "veriwasi"
crate_type = ["dylib"]

[dependencies]
system-call = "0.1.3"
prusti-contracts = { path = "prusti-dev/prusti-contracts" }
libc = "0.2"
trace = "*"
extra_args = "0.1.4"


[features]
verify = ["extra_args/enable"] # feature for when we're verifying
