[package]
name = "veriwasi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
system-call = "0.1.3"
prusti-contracts = { path = "prusti-dev/prusti-contracts" }
libc = "0.2"

[features]
verify = [] # feature for when we're verifying
