[package]
name = "wrappers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smack = { path = "/usr/local/share/smack/lib" }
system-call = "0.1.3"

[profile.dev]
incremental=false

