#ifndef veriwasi_bindings_h
#define veriwasi_bindings_h

/* Generated with cbindgen:0.20.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define MAX_SBOX_FDS 8

#define MAX_HOST_FDS 1024

#define PATH_MAX 1024

#define PAGE_SIZE 4096

#define LINEAR_MEM_SIZE 4294965096

typedef struct VmCtx VmCtx;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct VmCtx *veriwasi_init(uint8_t *memptr, intptr_t memsize);

uint32_t Z_wasi_snapshot_preview1Z_args_getZ_iii(void*ctx,
                                                  uint32_t argv,
                                                  uint32_t argv_buf);

uint32_t Z_wasi_snapshot_preview1Z_args_sizes_getZ_iii(void* ctx,
                                                        uint32_t pargc,
                                                        uint32_t pargv_buf_size);

void Z_wasi_snapshot_preview1Z_proc_exitZ_vi(void* ctx, uint32_t x);

uint32_t Z_wasi_snapshot_preview1Z_environ_sizes_getZ_iii(void* ctx,
                                                           uint32_t pcount,
                                                           uint32_t pbuf_size);

uint32_t Z_wasi_snapshot_preview1Z_environ_getZ_iii(void* ctx,
                                                     uint32_t __environ,
                                                     uint32_t environ_buf);

uint32_t Z_wasi_snapshot_preview1Z_fd_prestat_getZ_iii(void* ctx,
                                                        uint32_t fd,
                                                        uint32_t prestat);

uint32_t Z_wasi_snapshot_preview1Z_fd_writeZ_iiiii(void* ctx,
                                                    uint32_t fd,
                                                    uint32_t iov,
                                                    uint32_t iovcnt,
                                                    uint32_t pnum);

uint32_t Z_wasi_snapshot_preview1Z_fd_readZ_iiiii(void* ctx,
                                                   uint32_t fd,
                                                   uint32_t iov,
                                                   uint32_t iovcnt,
                                                   uint32_t pnum);

uint32_t Z_wasi_snapshot_preview1Z_fd_closeZ_ii(void* ctx,
                                                 uint32_t fd);

uint32_t Z_wasi_snapshot_preview1Z_fd_seekZ_iijii(void* ctx,
                                                   uint32_t fd,
                                                   uint64_t offset,
                                                   uint32_t whence,
                                                   uint32_t new_offset);

uint32_t Z_wasi_snapshot_preview1Z_fd_seekZ_iiiiii(void* ctx,
                                                    uint32_t a,
                                                    uint32_t b,
                                                    uint32_t c,
                                                    uint32_t d,
                                                    uint32_t e);

uint32_t Z_wasi_snapshot_preview1Z_clock_time_getZ_iiji(void* ctx,
                                                         uint32_t clock_id,
                                                         uint64_t max_lag,
                                                         uint32_t out);

uint32_t Z_wasi_snapshot_preview1Z_clock_res_getZ_iii(void* ctx,
                                                       uint32_t clock_id,
                                                       uint32_t out);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* veriwasi_bindings_h */
